const investorData = [

  {
    id: 1,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Monthly",
    type: "Commercial",
    amount: "₹50,000",
    share: "1.2%",
    status: "Active",
  },

  {
    id: 2,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Yearly",
    type: "Residential",
    amount: "₹50,000",
    share: "1.2%",
    status: "Cancelled",
  },

  {
    id: 3,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Monthly",
    type: "Residential",
    amount: "₹50,000",
    share: "1.2%",
    status: "Matured",
  },

  {
    id: 4,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Yearly",
    type: "Commercial",
    amount: "₹50,000",
    share: "1.2%",
    status: "Pending",
  },
  {
    id: 5,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Monthly",
    type: "Commercial",
    amount: "₹50,000",
    share: "1.2%",
    status: "Active",
  },

  {
    id: 6,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Yearly",
    type: "Residential",
    amount: "₹50,000",
    share: "1.2%",
    status: "Cancelled",
  },

  {
    id: 7,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Monthly",
    type: "Residential",
    amount: "₹50,000",
    share: "1.2%",
    status: "Matured",
  },

  {
    id: 8,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Yearly",
    type: "Commercial",
    amount: "₹50,000",
    share: "1.2%",
    status: "Pending",
  },

  {
    id: 9,
    name: "Nitya Varma",
    date: "12 Jul 2025",
    property: "2 BHK Apartment",
    location: "Andheri East, Mumbai",
    plan: "Monthly",
    type: "Residential",
    amount: "₹50,000",
    share: "1.2%",
    status: "Matured",
  },
];